
# This is params file used to configure launching the ROS2 part of testbench
# This params file is used extensively by loading_motor_dt package.
# Here we define namespaces that follow the defined preset names, e.g. we have only 2 loading motors
# thus we will have tb_lm_left("testbench loading motor right") and tb_lm_right("testbench loading motor left")
# NB! please write full paths for filenames, as there is a bug that relative names are not resolved.

tb_lm_left:
  current_simulator:
    ros__parameters:
      run_forever: True
      num_of_cols: 12
      filename: "measurement_malfunction.csv"
      frequency: 1000

  efficiency_map:
    ros__parameters:
      filename: "PMSynRM.csv"

  windings_checker:
    ros__parameters:
      matlab_path: ""
      buffer_size: 1000
      error_margin: 0.15
  
  power_calculator:
    ros__parameters:
      buffer_size: 1000

tb_lm_right:
  current_simulator:
    ros__parameters:
      run_forever: True
      num_of_cols: 12
      filename: "measurement_malfunction.csv"
      frequency: 1000

  efficiency_map:
    ros__parameters:
      filename: "PMSynRM.csv"

  windings_checker:
    ros__parameters:
      matlab_path: ""
      buffer_size: 1000
      error_margin: 0.15
  
  power_calculator:
    ros__parameters:
      buffer_size: 1000  

tb_tm:
  current_simulator:
    ros__parameters:
      run_forever: True
      num_of_cols: 12
      filename: "1k_ros_work.csv"
      frequency: 1000
